# Configuración del servidor web
server:
  port: 8080  # El puerto en el que la aplicación Spring Boot se ejecutará

spring:
  application:
    name: Home # Nombre de la aplicación, útil para identificarla en logs o servicios

  r2dbc:
    url: ${DATABASE_URL}  # URL para conexión a base de datos reactiva (R2DBC), tomada de variable de entorno DATABASE_URL

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}       # URI del emisor del JWT (proveedor de tokens), tomada de variable de entorno
          jwk-set-uri: ${JWT_JWK_SET_URI}     # URI para obtener claves públicas JWK para validar tokens JWT
